<?php

namespace Database\Seeders;

use App\Models\AuditRule;
use Illuminate\Database\Seeder;

class AuditRuleSeeder extends Seeder
{
    public function run(): void
    {
        $rules = [
            // SEO Pillar
            [
                'id' => 'seo_title_missing',
                'category' => 'seo',
                'title' => 'Missing HTML Title Tag',
                'severity' => 'critical',
                'default_weight' => 2.0,
                'impact_description' => 'The page has no <title> tag, preventing search engines from displaying an accurate headline in search snippets.',
                'why_it_matters' => 'Search engines use the title tag as the primary headline in SERPs and browser tabs. Without it, click-through rates plummet.',
                'fix_guidance' => 'Add a descriptive, unique <title> element inside the <head> of the document (recommended 50–60 characters).',
                'technical_fix_guidance' => '<head>\n  <title>Descriptive Primary Title - Brand Name</title>\n</head>',
            ],
            [
                'id' => 'seo_title_length',
                'category' => 'seo',
                'title' => 'Title Tag Length Suboptimal',
                'severity' => 'medium',
                'default_weight' => 1.0,
                'impact_description' => 'The title tag is either too short (< 30 chars) or exceeds recommended display limits (> 65 chars).',
                'why_it_matters' => 'Overly long titles get truncated with an ellipsis (...) in SERPs, whereas short titles miss valuable descriptive context.',
                'fix_guidance' => 'Target 50–60 characters (~580 pixels width) to prevent truncation while ensuring strong search intent match.',
                'technical_fix_guidance' => 'Keep the core keyword near the beginning, followed by brand suffix: "Primary Value Proposition | Brand"',
            ],
            [
                'id' => 'seo_meta_desc_missing',
                'category' => 'seo',
                'title' => 'Missing Meta Description',
                'severity' => 'high',
                'default_weight' => 1.5,
                'impact_description' => 'No <meta name="description"> tag was discovered on the page.',
                'why_it_matters' => 'Search engines may generate their own snippet by pulling random text from the page instead of your curated summary.',
                'fix_guidance' => 'Add an enticing, unique meta description between 140 and 160 characters summarizing the page value.',
                'technical_fix_guidance' => '<meta name="description" content="Discover actionable insights and fast website audits with W3HealthChecker. Scan your site free today.">',
            ],
            [
                'id' => 'seo_meta_desc_length',
                'category' => 'seo',
                'title' => 'Meta Description Length Suboptimal',
                'severity' => 'medium',
                'default_weight' => 1.0,
                'impact_description' => 'The meta description length is outside the ideal 120–160 character boundary.',
                'why_it_matters' => 'Descriptions shorter than 70 characters lack substance; descriptions longer than 160 characters are truncated.',
                'fix_guidance' => 'Refine the meta description to roughly 140–160 characters with a clear call-to-action.',
                'technical_fix_guidance' => 'Audit description length with mb_strlen() or character counter before publishing.',
            ],
            [
                'id' => 'seo_h1_missing',
                'category' => 'seo',
                'title' => 'Missing Primary Heading (H1)',
                'severity' => 'high',
                'default_weight' => 1.5,
                'impact_description' => 'No <h1> heading was located in the HTML markup.',
                'why_it_matters' => 'The <h1> element is the semantic cornerstone of page hierarchy for both search crawlers and screen readers.',
                'fix_guidance' => 'Include exactly one clear, topic-focused <h1> element that encapsulates the primary topic of the page.',
                'technical_fix_guidance' => '<h1>Your Primary Page Topic</h1>',
            ],
            [
                'id' => 'seo_h1_multiple',
                'category' => 'seo',
                'title' => 'Multiple H1 Headings Detected',
                'severity' => 'low',
                'default_weight' => 0.5,
                'impact_description' => 'The page contains more than one <h1> element.',
                'why_it_matters' => 'While HTML5 permits multiple H1s, best practice for clear topical focus and accessibility hierarchy is having a single H1 per document.',
                'fix_guidance' => 'Use a single <h1> for the page title and demote secondary section headings to <h2>.',
                'technical_fix_guidance' => 'Change secondary <h1> tags to <h2> in your template.',
            ],
            [
                'id' => 'seo_canonical_missing',
                'category' => 'seo',
                'title' => 'Missing Canonical URL Tag',
                'severity' => 'medium',
                'default_weight' => 1.0,
                'impact_description' => 'No <link rel="canonical"> tag was found.',
                'why_it_matters' => 'Without canonical tags, search engines may index duplicate URL variations (HTTP/HTTPS, trailing slashes, tracking parameters).',
                'fix_guidance' => 'Add a self-referencing canonical link to the master URL version.',
                'technical_fix_guidance' => '<link rel="canonical" href="https://example.com/page-url">',
            ],
            [
                'id' => 'seo_canonical_mismatch',
                'category' => 'seo',
                'title' => 'Canonical URL Mismatch / Inconsistency',
                'severity' => 'high',
                'default_weight' => 1.5,
                'impact_description' => 'The canonical URL points to a different domain, scheme, or path than the requested address.',
                'why_it_matters' => 'If unintentional, search engines will consolidate authority away from this URL to the canonical target.',
                'fix_guidance' => 'Verify that the canonical link reflects the exact desired indexed URL.',
                'technical_fix_guidance' => 'Ensure scheme (https://), host, and trailing slashes match your canonical standard.',
            ],
            [
                'id' => 'seo_images_missing_alt',
                'category' => 'seo',
                'title' => 'Images Missing Alt Attributes',
                'severity' => 'medium',
                'default_weight' => 1.0,
                'impact_description' => 'One or more <img> tags do not specify an alt attribute.',
                'why_it_matters' => 'Search crawlers use alt text to understand image content for image search indexing; screen readers rely on it for visually impaired users.',
                'fix_guidance' => 'Add concise, descriptive alt text to all informative images. Use alt="" only for purely decorative graphics.',
                'technical_fix_guidance' => '<img src="/hero.webp" alt="Website health scan dashboard preview">',
            ],
            [
                'id' => 'seo_robots_blocking',
                'category' => 'seo',
                'title' => 'Page Disallowed or Set to Noindex',
                'severity' => 'critical',
                'default_weight' => 2.5,
                'impact_description' => 'A meta robots "noindex" or robots.txt Disallow rule blocks crawlers from indexing this page.',
                'why_it_matters' => 'The page will be purged or excluded from search engine indexes entirely.',
                'fix_guidance' => 'Remove <meta name="robots" content="noindex"> and check robots.txt unless this page is intentionally private.',
                'technical_fix_guidance' => '<meta name="robots" content="index, follow">',
            ],
            [
                'id' => 'seo_sitemap_missing',
                'category' => 'seo',
                'title' => 'XML Sitemap Undetected or Inaccessible',
                'severity' => 'medium',
                'default_weight' => 1.0,
                'impact_description' => 'Could not detect an XML sitemap at /sitemap.xml or declared inside robots.txt.',
                'why_it_matters' => 'XML sitemaps help crawlers discover new and updated URLs efficiently.',
                'fix_guidance' => 'Generate a valid sitemap.xml and declare "Sitemap: https://yourdomain.com/sitemap.xml" in your robots.txt.',
                'technical_fix_guidance' => 'Sitemap: https://example.com/sitemap.xml inside /robots.txt',
            ],

            // Security Pillar
            [
                'id' => 'sec_https_missing',
                'category' => 'security',
                'title' => 'Not Operating Over Secure HTTPS',
                'severity' => 'critical',
                'default_weight' => 3.0,
                'impact_description' => 'The website is served over insecure HTTP or fails to enforce TLS encryption.',
                'why_it_matters' => 'Browsers mark HTTP sites as "Not Secure", user data is vulnerable to packet interception, and modern search engines penalize unencrypted pages.',
                'fix_guidance' => 'Install a valid SSL/TLS certificate and enforce a 301 permanent redirect from HTTP to HTTPS.',
                'technical_fix_guidance' => 'Configure web server (Nginx/Apache) to redirect port 80 to port 443 with TLS 1.3.',
            ],
            [
                'id' => 'sec_hsts_missing',
                'category' => 'security',
                'title' => 'Missing Strict-Transport-Security (HSTS) Header',
                'severity' => 'high',
                'default_weight' => 1.5,
                'impact_description' => 'The Strict-Transport-Security response header is absent.',
                'why_it_matters' => 'HSTS forces modern browsers to communicate only via HTTPS, protecting visitors from SSL-stripping and man-in-the-middle attacks.',
                'fix_guidance' => 'Add the Strict-Transport-Security header with a minimum max-age of 31536000 (1 year) and includeSubDomains.',
                'technical_fix_guidance' => 'Strict-Transport-Security: max-age=31536000; includeSubDomains; preload',
            ],
            [
                'id' => 'sec_csp_missing',
                'category' => 'security',
                'title' => 'Missing Content-Security-Policy (CSP)',
                'severity' => 'medium',
                'default_weight' => 1.0,
                'impact_description' => 'No Content-Security-Policy header was detected on the response.',
                'why_it_matters' => 'CSP restricts the scripts, styles, and media domains allowed to execute, acting as the primary defense against Cross-Site Scripting (XSS).',
                'fix_guidance' => 'Deploy a Content-Security-Policy header starting in report-only mode or with safe defaults.',
                'technical_fix_guidance' => "Content-Security-Policy: default-src 'self'; script-src 'self' 'nonce-...'; object-src 'none';",
            ],
            [
                'id' => 'sec_x_content_type_missing',
                'category' => 'security',
                'title' => 'Missing X-Content-Type-Options Header',
                'severity' => 'medium',
                'default_weight' => 1.0,
                'impact_description' => 'The X-Content-Type-Options: nosniff header is missing.',
                'why_it_matters' => 'Without this header, older or compliant browsers may MIME-sniff response payloads away from the declared content-type, creating XSS vectors.',
                'fix_guidance' => 'Set X-Content-Type-Options: nosniff on all HTTP responses.',
                'technical_fix_guidance' => 'X-Content-Type-Options: nosniff',
            ],
            [
                'id' => 'sec_x_frame_missing',
                'category' => 'security',
                'title' => 'Missing Clickjacking Defense (X-Frame-Options / frame-ancestors)',
                'severity' => 'medium',
                'default_weight' => 1.0,
                'impact_description' => 'Neither X-Frame-Options nor CSP frame-ancestors was found.',
                'why_it_matters' => 'Attackers can embed your site into hidden iframe layers on malicious domains to trick users into clicking buttons (Clickjacking).',
                'fix_guidance' => 'Set X-Frame-Options: SAMEORIGIN or use CSP frame-ancestors.',
                'technical_fix_guidance' => 'X-Frame-Options: SAMEORIGIN',
            ],
            [
                'id' => 'sec_referrer_policy_missing',
                'category' => 'security',
                'title' => 'Missing or Permissive Referrer-Policy',
                'severity' => 'low',
                'default_weight' => 0.5,
                'impact_description' => 'No Referrer-Policy header is configured.',
                'why_it_matters' => 'Referrer headers may leak private query parameters, internal paths, or user tokens to third-party domains when links are clicked.',
                'fix_guidance' => 'Set Referrer-Policy: strict-origin-when-cross-origin.',
                'technical_fix_guidance' => 'Referrer-Policy: strict-origin-when-cross-origin',
            ],
            [
                'id' => 'sec_sensitive_file_exposure',
                'category' => 'security',
                'title' => 'Potential Sensitive Endpoint Exposure Detected',
                'severity' => 'critical',
                'default_weight' => 3.0,
                'impact_description' => 'A passive check discovered that endpoints such as .env, .git, or backups returned HTTP 200.',
                'why_it_matters' => 'Exposing configuration files or version control directories can lead to complete compromise of credentials and source code.',
                'fix_guidance' => 'Immediately restrict access to hidden dotfiles and backup files in your web server configuration.',
                'technical_fix_guidance' => 'In Nginx: location ~ /\\.(?!well-known) { deny all; }\nIn Apache: RedirectMatch 404 /\\.(git|env)',
            ],

            // Performance Pillar
            [
                'id' => 'perf_slow_response',
                'category' => 'performance',
                'title' => 'High Server Response Time (TTFB)',
                'severity' => 'high',
                'default_weight' => 2.0,
                'impact_description' => 'The server took longer than 800ms to return the initial HTML document.',
                'why_it_matters' => 'Slow initial server response delays every downstream rendering milestone, inflating Largest Contentful Paint (LCP).',
                'fix_guidance' => 'Implement server-side caching (Redis, OPcache), optimize database queries, or place a CDN reverse proxy in front of the origin.',
                'technical_fix_guidance' => 'Use page-level reverse-proxy caching (Fastly, Cloudflare) and opcode caching.',
            ],
            [
                'id' => 'perf_uncompressed_html',
                'category' => 'performance',
                'title' => 'HTML Text Compression Not Detected',
                'severity' => 'high',
                'default_weight' => 1.5,
                'impact_description' => 'The server did not respond with gzip, brotli, or zstd content-encoding.',
                'why_it_matters' => 'Modern compression algorithms reduce text payload size by 65%–85%, speeding up transmission over mobile networks.',
                'fix_guidance' => 'Enable Gzip or Brotli compression on your web server for HTML, CSS, JS, and SVG assets.',
                'technical_fix_guidance' => 'In Nginx: gzip on; gzip_types text/html text/css application/javascript application/json;\nOr brotli_static on;',
            ],
            [
                'id' => 'perf_heavy_dom',
                'category' => 'performance',
                'title' => 'Large Document HTML Payload',
                'severity' => 'medium',
                'default_weight' => 1.0,
                'impact_description' => 'The uncompressed HTML document exceeds 150KB.',
                'why_it_matters' => 'Bloated HTML increases parse times on mobile devices and burns visitor bandwidth.',
                'fix_guidance' => 'Remove inlined base64 images or excessive inline scripts; paginate large data tables.',
                'technical_fix_guidance' => 'Extract inline SVG icons and inline scripts to external cached files.',
            ],
            [
                'id' => 'perf_excessive_scripts',
                'category' => 'performance',
                'title' => 'High Volume of External JavaScript Files',
                'severity' => 'medium',
                'default_weight' => 1.0,
                'impact_description' => 'The page references more than 15 separate JavaScript script tags.',
                'why_it_matters' => 'Excessive scripts cause network congestion and JavaScript main-thread contention, degrading Interaction to Next Paint (INP).',
                'fix_guidance' => 'Bundle scripts, defer non-essential scripts with defer or async, and remove unused libraries.',
                'technical_fix_guidance' => '<script src="analytics.js" defer></script>',
            ],
            [
                'id' => 'perf_missing_lazy_loading',
                'category' => 'performance',
                'title' => 'Images Missing Native Lazy Loading',
                'severity' => 'low',
                'default_weight' => 0.5,
                'impact_description' => 'Images outside the initial viewport do not specify loading="lazy".',
                'why_it_matters' => 'Offscreen images load immediately on page start, competing with critical above-the-fold assets for bandwidth.',
                'fix_guidance' => 'Add loading="lazy" and decoding="async" to all below-the-fold images.',
                'technical_fix_guidance' => '<img src="footer-logo.png" loading="lazy" decoding="async" alt="...">',
            ],

            // Accessibility Pillar
            [
                'id' => 'a11y_html_lang_missing',
                'category' => 'accessibility',
                'title' => 'Missing or Invalid HTML Lang Attribute',
                'severity' => 'high',
                'default_weight' => 1.5,
                'impact_description' => 'The <html> root tag has no lang attribute (e.g. lang="en").',
                'why_it_matters' => 'Screen readers need the language code to select the correct speech synthesizer pronunciation rules.',
                'fix_guidance' => 'Add a valid BCP 47 language code to the <html> tag.',
                'technical_fix_guidance' => '<html lang="en">',
            ],
            [
                'id' => 'a11y_empty_buttons',
                'category' => 'accessibility',
                'title' => 'Buttons Without Accessible Names',
                'severity' => 'high',
                'default_weight' => 1.5,
                'impact_description' => 'One or more <button> tags contain no textual content, aria-label, or aria-labelledby.',
                'why_it_matters' => 'Users relying on screen readers hear "button" with no indication of what clicking it will do.',
                'fix_guidance' => 'Add descriptive text inside the button or use aria-label="Close menu".',
                'technical_fix_guidance' => '<button aria-label="Search website"><svg>...</svg></button>',
            ],
            [
                'id' => 'a11y_empty_links',
                'category' => 'accessibility',
                'title' => 'Links Without Discernible Text',
                'severity' => 'high',
                'default_weight' => 1.5,
                'impact_description' => 'Anchor <a> tags without text or aria-label were detected.',
                'why_it_matters' => 'Screen reader users navigating via links cannot determine the destination.',
                'fix_guidance' => 'Provide clear link text or an aria-label describing the link target.',
                'technical_fix_guidance' => '<a href="/cart" aria-label="View shopping cart"><i class="icon-cart"></i></a>',
            ],

            // Mobile Pillar
            [
                'id' => 'mobile_viewport_missing',
                'category' => 'mobile',
                'title' => 'Missing Viewport Meta Tag',
                'severity' => 'critical',
                'default_weight' => 2.5,
                'impact_description' => 'No <meta name="viewport"> tag was detected.',
                'why_it_matters' => 'Mobile browsers will render the website as a desktop layout at 980px and shrink it down, making text illegible.',
                'fix_guidance' => 'Add the standard responsive viewport meta tag to the <head>.',
                'technical_fix_guidance' => '<meta name="viewport" content="width=device-width, initial-scale=1.0">',
            ],

            // Technical Pillar
            [
                'id' => 'tech_redirect_chain',
                'category' => 'technical',
                'title' => 'Excessive Redirect Chain Detected',
                'severity' => 'medium',
                'default_weight' => 1.0,
                'impact_description' => 'The target URL underwent 2 or more redirect hops before reaching final destination.',
                'why_it_matters' => 'Each redirect hop adds latency, wastes crawl budget, and can dilute link equity.',
                'fix_guidance' => 'Update internal links and server rules to redirect directly to the final canonical URL in a single 301 hop.',
                'technical_fix_guidance' => 'Example: http://site.com -> https://site.com -> https://www.site.com should be consolidated into one hop.',
            ],
            [
                'id' => 'tech_server_version_exposed',
                'category' => 'technical',
                'title' => 'Detailed Server Software / Version Exposed',
                'severity' => 'low',
                'default_weight' => 0.5,
                'impact_description' => 'The Server or X-Powered-By response header exposes exact software versions.',
                'why_it_matters' => 'Exposing software version fingerprints aids automated scanners in targeting known CVE vulnerabilities.',
                'fix_guidance' => 'Disable server signature tokens and remove X-Powered-By headers.',
                'technical_fix_guidance' => 'In php.ini: expose_php = Off\nIn Nginx: server_tokens off;',
            ],

            // AI & Search Readiness Pillar
            [
                'id' => 'ai_structured_data_missing',
                'category' => 'ai_readiness',
                'title' => 'No Structured Schema Data Found (JSON-LD / Microdata)',
                'severity' => 'medium',
                'default_weight' => 1.5,
                'impact_description' => 'No schema.org structured data (JSON-LD or Microdata) was detected on the page.',
                'why_it_matters' => 'Search engines and modern AI discovery engines rely heavily on machine-readable schema (Organization, WebSite, Article, Product) to extract entity relationships.',
                'fix_guidance' => 'Embed valid schema.org JSON-LD describing your organization, page type, or primary entity.',
                'technical_fix_guidance' => '<script type="application/ld+json">\n{\n  "@context": "https://schema.org",\n  "@type": "WebSite",\n  "name": "Your Brand",\n  "url": "https://example.com"\n}\n</script>',
            ],
            [
                'id' => 'ai_llms_txt_missing',
                'category' => 'ai_readiness',
                'title' => 'No llms.txt File Detected',
                'severity' => 'info',
                'default_weight' => 0.2,
                'impact_description' => 'No /llms.txt file was found at the root of the domain.',
                'why_it_matters' => 'The emerging /llms.txt standard helps AI search assistants and language models efficiently discover curated markdown documentation. (Note: Presence does not guarantee AI rankings).',
                'fix_guidance' => 'Consider publishing an /llms.txt file summarizing your site structure and primary resources in clean markdown.',
                'technical_fix_guidance' => 'Create a concise markdown file at https://example.com/llms.txt summarizing project docs and APIs.',
            ],
            [
                'id' => 'ai_robots_ai_crawlable',
                'category' => 'ai_readiness',
                'title' => 'AI Search Crawler Directives',
                'severity' => 'info',
                'default_weight' => 0.5,
                'impact_description' => 'robots.txt accessibility verified for standard and AI-assisted search user-agents.',
                'why_it_matters' => 'Explicit directives control whether generative search engines (like GPTBot, ClaudeBot, PerplexityBot) can index content for answers.',
                'fix_guidance' => 'Ensure robots.txt explicitly allows or manages AI search bots according to your content syndication strategy.',
                'technical_fix_guidance' => 'User-agent: GPTBot\nAllow: /',
            ],
        ];

        foreach ($rules as $rule) {
            AuditRule::updateOrCreate(['id' => $rule['id']], $rule);
        }
    }
}
