<?php

return [
    'plans' => [
        'free' => [
            'id' => 'free',
            'name' => 'Free Community',
            'tagline' => 'Essential website auditing for solo creators & site owners',
            'price_monthly' => 0,
            'max_monitored_websites' => 1,
            'max_projects' => 1,
            'max_scans_per_month' => 50,
            'history_days' => 14,
            'features' => [
                'all_free_tools' => true,
                'full_scans' => true,
                'weekly_monitoring' => true,
                'daily_monitoring' => false,
                'pdf_export' => false,
                'api_access' => false,
                'team_members' => false,
                'white_label' => false,
            ],
            'highlighted_features' => [
                '19 Free Specialized Audit Tools',
                'Full 7-Pillar Health Scans',
                '1 Monitored Website (Weekly)',
                '1 Personal Workspace Project',
                '14-Day History Retention',
            ],
        ],
        'pro' => [
            'id' => 'pro',
            'name' => 'Pro Webmaster',
            'tagline' => 'Advanced monitoring & deep change detection for growth teams',
            'price_monthly' => 29,
            'max_monitored_websites' => 10,
            'max_projects' => 5,
            'max_scans_per_month' => 500,
            'history_days' => 90,
            'features' => [
                'all_free_tools' => true,
                'full_scans' => true,
                'weekly_monitoring' => true,
                'daily_monitoring' => true,
                'pdf_export' => true,
                'api_access' => false,
                'team_members' => false,
                'white_label' => false,
            ],
            'highlighted_features' => [
                'Everything in Free',
                '10 Monitored Websites (Daily/Weekly)',
                '5 Workspace Projects',
                'Instant Regression Change Alerts',
                '90-Day History & Score Trendlines',
                'PDF Health Report Exports',
            ],
        ],
        'agency' => [
            'id' => 'agency',
            'name' => 'Agency & Teams',
            'tagline' => 'Multi-client portfolio intelligence, white-labeling & API access',
            'price_monthly' => 99,
            'max_monitored_websites' => 50,
            'max_projects' => 25,
            'max_scans_per_month' => 5000,
            'history_days' => 365,
            'features' => [
                'all_free_tools' => true,
                'full_scans' => true,
                'weekly_monitoring' => true,
                'daily_monitoring' => true,
                'pdf_export' => true,
                'api_access' => true,
                'team_members' => true,
                'white_label' => true,
            ],
            'highlighted_features' => [
                'Everything in Pro',
                '50 Monitored Websites',
                '25 Client Projects & Workspaces',
                'White-Label Client Reports',
                'REST API v1 Access & Tokens',
                'Team Member Collaboration',
                '1-Year History & Trend Graphing',
            ],
        ],
    ],
];
